[package]
name = "cli-llm-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
llama_cpp = "*"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }

